language: c
sudo: true
dist: trusty
compiler: gcc

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-6
    - g++-6

install:
- gcc -v
# - nim -v
# - nim e install_tools.nims
# - ln -s $HOME/.nimble/bin/nimble /usr/local/bin/nimble
# - nimble -v

script:
- exit 1
- nimble install
- make test
